### ISSUE TITLE
right menu action

### ISSUE THREAD

**Issue by dnamna** [aryaxt/iOS-Slide-Menu#165]
Is it possible to open the right menu table  from left to right.
I mean when you open the right menu you get the right side of the table.But what I need to show is the left side of the table.
Thx

**Comment by aryaxt** [comment]
this feature doesn't exist , you can fork and modify

thanks

**Comment by dnamna** [comment]
thanks to be honest am a newbie in ios but can you help a little bit like tell me where should I look because I don't know why I can't debug into the function animatemenu

**Comment by aryaxt** [comment]
You probably can't debug it because the animator is nil, if you open the right menu from sample and pick an animation then you can debug it.

In order to customize the animation look at here: https://github.com/aryaxt/iOS-Slide-Menu#custom-animations

Not sure how you are planning to animate, but if the navigationcontroller is not moving on the screen, and the menu just appears on top of it, then you don't wanna use this lib, there are much simpler ways to implement a side menu similar to gmail or inbox.
