### ISSUE TITLE
Can't create SlideNavigationController

### ISSUE THREAD

**Issue by caraldel** [aryaxt/iOS-Slide-Menu#198]
I'm trying to create a left slide menu with your approach. My entry point in the StoryBoard isn't the SlideNavigationController and when I load the view with is root view of the SlideNavigationController, there is a message in the console: "SlideNavigationController has not been initialized. Either place one in your storyboard or initialize one in code" and the left bar button doesn't appear and when I slide the view, the left menu is 'black'. Do you know why ?

Thanks.

**Comment by SCLDev** [comment]
I had the same problem, and I found it was because the navigation controller wasn't the starting point. I had a login view, that was not supposed to be passed through without authentication.

This is what I did to get around the issue:

1. start with the navigation controller as the entry point. 
2. set the navigation buttons to no (both right and left methods, check the documentation for the two delegate methods).
3. I didn't want to show the navigation controller bar either, so I set the bar to be hidden when the login view was loaded (viewDidAppear or viewWillAppear).
4. unhide the bar when leaving the view (viewDidDisappear / viewWillDisappear)
5. use the popAllToRootViewController.... method of the SlideNavigationController to navigate to the new view (the one that you want to show the buttons on), set the menu buttons using the two method (check documentation).
6. It's pretty much done. One thing, if you want to go back to the view that didn't have the buttons, just use the same popToRootViewController.... method. I even used a flag to make sure that the view won't show the menu.

I know my method may not be the best solution for you, but it works, and works really well.

Let me know if you found any more on that.

Sep

**Comment by mattiaskronberg** [comment]
Hi, @SCLDev , just wanted to thank you for your solution. I was stuck for hours...

**Comment by SCLDev** [comment]
@mattiaskronberg I'm glad you could use it.

**Comment by onderozcan** [comment]
I am really stuck that library too. No actual documentation in github page.  Demo application also confusing and i got same error "**SlideNavigationController has not been initialized. Either place one in your storyboard or initialize one in code**" even my first stack starting with Navigation Controller.

**Comment by aryaxt** [comment]
@onderozcan  the recommended use of SlideNavigationController is to be set as the rootViewController, you are seeing this error if you try to access the singleton instance before initializing the slideNavigationController.

https://github.com/aryaxt/iOS-Slide-Menu/blob/master/SlideMenu/Source/SlideNavigationController.m#L70
